i18n:
     name: "Preparing your system for ZeroLinux"

dontChroot: false
timeout: 999
script:
    - command: "/usr/local/bin/ZeroLinux-all-cores"
    - command: "/usr/local/bin/ZeroLinux-desktop-specific-x11"
    - command: "/usr/local/bin/ZeroLinux-desktop-specific-wayland"
    - command: "/usr/local/bin/ZeroLinux-displaymanager-check"
    - command: "/usr/local/bin/ZeroLinux-fixes"
    - command: "/usr/local/bin/ZeroLinux-set-bootloader"
    - command: "/usr/local/bin/ZeroLinux-system"
    - command: "/usr/local/bin/ZeroLinux-nvidia-settings"
    - command: "/usr/local/bin/ZeroLinux-virtual-machine-check"
    - command: "/usr/bin/pacman -R --noconfirm zerolinux-system-installation"