i18n:
     name: "Preparing your system for ZeroLinux"

dontChroot: false
timeout: 999
script:
    - command: "/usr/local/bin/ZeroLinux-before"
    - command: "/usr/local/bin/ZeroLinux-remove-nvidia"
